function [rising_Edges] = ...
    EdgeDetect_Rise(dataDiff, dataDiffOffset, pow_Low, pow_High)
rising_Edges = find(...
        dataDiff < pow_Low & ...
        dataDiffOffset > pow_Low & ...
        dataDiffOffset < pow_High ...
        );
end