function [Table] = GenTable(DataFinal)
Table = table();
for i = 1:length(DataFinal(end).edge_Rise)
        newRow = {DataFinal(end).edge_Rise(i),...
                  DataFinal(end).edge_Fall(i),...
                  DataFinal(end).StartTime(i),...
                  DataFinal(end).EndTime(i),...
                  DataFinal(end).Duration(i),...
                  DataFinal(end).kWh(i)};
        Table = [Table;newRow;];
end
end

